apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    tier: database
spec:
  type: ClusterIP  # Servicio interno (no accesible desde fuera del cluster)
  selector:
    app: postgres  # Debe coincidir con las labels del Deployment
  ports:
    - name: postgres
      protocol: TCP
      port: 5432    # Puerto expuesto por el servicio
      targetPort: 5432  # Puerto del contenedor PostgreSQL